# Generated by Django 3.1.1 on 2020-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
